[eval exp="f.count = 0"]
[macro name="fixed"]
[eval exp="f.count = f.count + 1"]
[ch text="静态宏 ${f.count}"]
[endmacro]
[fixed]
[macro name="dynamic"]
[eval exp="f.count = f.count + 1"]
[ch text="动态甲 ${f.count}"]
[endmacro]
[dynamic]
[macro name="dynamic"]
[eval exp="f.count = f.count + 1"]
[ch text="动态乙 ${f.count}"]
[endmacro]
[dynamic]
[end]
