#!/usr/bin/env python3
"""Generate runtime catalog data without opening config/ in the Lua sandbox."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "config" / "runtime-capabilities.json"
STATES = {"supported", "approximate", "unsupported"}
COMPILED = {"ffmpeg", "live2d", "steam"}
AVAILABLE = {
    "postfx.bloom", "postfx.vignette", "postfx.lut", "postfx.softblur",
    "postfx.lut3d", "particles", "video", "audio", "cubism", "steam",
}


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate catalog key")
        result[key] = value
    return result


def render(source):
    # Git's platform line-ending conversion must not change catalog identity.
    text = source.read_text(encoding="utf-8").replace("\r\n", "\n")
    data = json.loads(text, object_pairs_hook=unique_object)
    if data.get("schema") != 1 or not isinstance(data.get("features"), dict):
        raise ValueError("invalid catalog schema")
    for feature, targets in data["features"].items():
        if not re.fullmatch(r"[a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)+", feature):
            raise ValueError("invalid feature key")
        if not isinstance(targets, dict) or set(targets) != {"native", "web"}:
            raise ValueError("both catalog targets are required")
        for record in targets.values():
            if not isinstance(record, dict) or record.get("status") not in STATES:
                raise ValueError("invalid capability status")
            if set(record) - {"status", "reason", "compiled", "available"}:
                raise ValueError("unknown capability property")
            if record["status"] != "supported" and not isinstance(record.get("reason"), str):
                raise ValueError("non-exact capability requires a reason")
            if "compiled" in record and record["compiled"] not in COMPILED:
                raise ValueError("unknown compiled fact")
            if "available" in record and record["available"] not in AVAILABLE:
                raise ValueError("unknown availability fact")
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    payload = json.dumps(data, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    delimiter = "="
    while "]" + delimiter + "]" in payload:
        delimiter += "="
    lua = (
        "-- Generated by scripts/generate_runtime_capabilities.py; edit config/runtime-capabilities.json.\n"
        "return {\n"
        f'    sha256 = "{digest}",\n'
        f"    json = [{delimiter}[{payload}]{delimiter}],\n"
        "}\n"
    )
    js = (
        "// Generated by scripts/generate_runtime_capabilities.py; edit config/runtime-capabilities.json.\n"
        f"export const catalogSha256 = {json.dumps(digest)}\n"
        f"export const catalogJson = {json.dumps(payload, ensure_ascii=False)}\n"
    )
    return {
        ROOT / "scripts" / "capability_catalog.lua": lua,
        ROOT / "web" / "capability-catalog.js": js,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        stale = []
        for path, content in render(SOURCE).items():
            if args.check:
                if not path.is_file() or path.read_text(encoding="utf-8") != content:
                    stale.append(path.relative_to(ROOT).as_posix())
            else:
                path.write_text(content, encoding="utf-8", newline="\n")
        if stale:
            print("Stale runtime capability catalog: " + ", ".join(stale), file=sys.stderr)
            return 1
        print("Runtime capability catalog " + ("is current" if args.check else "generated"))
        return 0
    except (OSError, ValueError, TypeError) as error:
        print("Runtime capability catalog failed: " + str(error), file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
