# Install the bytes behind a shared target under the name its loader requests.
# install(FILES <SONAME symlink>) preserves that link without installing its
# versioned target. Resolve TARGET_FILE at install time, including imported
# target aliases/chains and the selected install configuration.
function(caesura_install_shared_runtime target)
    if(ARGC GREATER 1)
        # FindOpenSSL creates UNKNOWN imported targets. Their selected file
        # still supports TARGET_FILE, but has no CMake SONAME/type declaration.
        # Require both linkage and the exact loader name for this opt-in path.
        cmake_parse_arguments(PARSE_ARGV 1 runtime "" "LINKAGE;RUNTIME_NAME" "")
        if(runtime_UNPARSED_ARGUMENTS OR runtime_KEYWORDS_MISSING_VALUES
           OR NOT DEFINED runtime_LINKAGE OR NOT DEFINED runtime_RUNTIME_NAME)
            message(FATAL_ERROR "Explicit runtime installation requires LINKAGE and RUNTIME_NAME")
        endif()
        if(NOT runtime_LINKAGE MATCHES "^(static|shared)$")
            message(FATAL_ERROR "Runtime LINKAGE must be static or shared")
        endif()
        if(NOT runtime_RUNTIME_NAME MATCHES "^[A-Za-z0-9][A-Za-z0-9._+-]*$")
            message(FATAL_ERROR "Runtime RUNTIME_NAME must be a plain loader filename")
        endif()
        if(NOT TARGET "${target}")
            message(FATAL_ERROR "Required runtime target is missing: ${target}")
        endif()
        get_target_property(runtime_type "${target}" TYPE)
        if(NOT runtime_type MATCHES "^(UNKNOWN_LIBRARY|STATIC_LIBRARY|SHARED_LIBRARY)$"
           OR (runtime_type STREQUAL "STATIC_LIBRARY" AND runtime_LINKAGE STREQUAL "shared")
           OR (runtime_type STREQUAL "SHARED_LIBRARY" AND runtime_LINKAGE STREQUAL "static"))
            message(FATAL_ERROR "Runtime target type contradicts explicit linkage: ${target}")
        endif()
        if(runtime_LINKAGE STREQUAL "static")
            return()
        endif()
        set(runtime_name "${runtime_RUNTIME_NAME}")
    else()
        if(NOT TARGET "${target}")
            return()
        endif()
        get_target_property(runtime_type "${target}" TYPE)
        if(NOT runtime_type STREQUAL "SHARED_LIBRARY")
            return()
        endif()
        if(WIN32)
            set(runtime_name "$<TARGET_FILE_NAME:${target}>")
        else()
            set(runtime_name "$<TARGET_SONAME_FILE_NAME:${target}>")
        endif()
    endif()
    set(runtime_install [=[
        set(_caesura_runtime_source "$<TARGET_FILE:@target@>")
        set(_caesura_runtime_name "@runtime_name@")
        if(NOT EXISTS "${_caesura_runtime_source}" OR IS_DIRECTORY "${_caesura_runtime_source}")
            message(FATAL_ERROR "Required shared runtime is missing: ${_caesura_runtime_source}")
        endif()
        if(_caesura_runtime_name STREQUAL "" OR _caesura_runtime_name MATCHES "[/\\]")
            message(FATAL_ERROR "Shared runtime requires a plain loader filename")
        endif()
        file(REAL_PATH "${_caesura_runtime_source}" _caesura_runtime_real)
        # Honor ordinary install prefix/DESTDIR behavior, but never let the
        # caller's install mode replace these required bytes with an SDK link.
        if(DEFINED ENV{CMAKE_INSTALL_MODE})
            set(_caesura_had_install_mode TRUE)
            set(_caesura_saved_install_mode "$ENV{CMAKE_INSTALL_MODE}")
        else()
            set(_caesura_had_install_mode FALSE)
        endif()
        set(ENV{CMAKE_INSTALL_MODE} COPY)
        file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/."
             TYPE FILE FILES "${_caesura_runtime_real}" RENAME "${_caesura_runtime_name}")
        if(_caesura_had_install_mode)
            set(ENV{CMAKE_INSTALL_MODE} "${_caesura_saved_install_mode}")
        else()
            unset(ENV{CMAKE_INSTALL_MODE})
        endif()
    ]=])
    string(CONFIGURE "${runtime_install}" runtime_install @ONLY)
    install(CODE "${runtime_install}")
endfunction()
