// @vitest-environment jsdom
// Full browser-flow integration: real wasmoon engine + DOM renderer +
// the complete galgame demo scene, driven click-by-click.
import { describe, it, expect, beforeAll } from 'vitest'
import { readFileSync, existsSync, statSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { createPlayer } from './bridge.js'
import { DomRenderer } from './dom-renderer.js'

const here = dirname(fileURLToPath(import.meta.url))
const rootDir = join(here, '..')
const scriptsDir = join(rootDir, 'scripts')
const assetsDir = join(rootDir, 'assets')
const index = JSON.parse(readFileSync(join(here, 'scripts-index.json'), 'utf8'))
// Round 91: also serve the REAL assets/lang/<code>.lua dictionaries so the
// bridge can mount them (i18n web parity). Any other non-script path 404s
// (the bridge treats a missing lang file as "use built-in", so a sensible
// test for the fallback chain must explicitly 404 an unserved code).
const fileFetch = async (url) => {
  const u = new URL(url)
  if (u.pathname.startsWith('/assets/lang/')) {
    const rel = u.pathname.replace('/assets/lang/', '')
    const p = join(assetsDir, 'lang', ...rel.split('/'))
    const isFile = existsSync(p) && statSync(p).isFile()
    return {
      ok: isFile,
      status: isFile ? 200 : 404,
      text: async () => (isFile ? readFileSync(p, 'utf8') : ''),
      json: async () => index,
    }
  }
  const rel = u.pathname.replace('/scripts/', '')
  const p = join(scriptsDir, ...rel.split('/'))
  const isFile = existsSync(p) && statSync(p).isFile()
  return {
    ok: isFile,
    status: isFile ? 200 : 404,
    text: async () => (isFile ? readFileSync(p, 'utf8') : ''),
    json: async () => index,
  }
}

// Sprint 1 / t3: the ks_bake --web artifact is gitignored (generated by
// scripts/package_game.sh step 2). Its absence must be a VISIBLE skip with the
// regeneration command, never a silent `return` that vitest reports as passed.
const bakedStoryPath = join(rootDir, 'cache', 'story', 'story.lua')
const hasBakedStory = existsSync(bakedStoryPath)
// checkout-executable interpreter (build/lua/Debug/lua.exe); the released
// package ships the interpreter at external/lua/lua.exe (gitignored, not in a
// fresh clone).
const BAKE_CMD = 'build/lua/Debug/lua.exe scripts/ks_bake.lua --dir demo --web cache/story'
if (!hasBakedStory) {
  // eslint-disable-next-line no-console
  console.warn('[flow.integration] cache/story/story.lua absent — the on-disk '
    + 'bundle case is SKIPPED (the in-process bundle case still runs). '
    + 'Regenerate with: ' + BAKE_CMD)
}

let player = null
let renderer = null
let stage = null

beforeAll(async () => {
  player = await createPlayer({
    scriptsBase: 'http://local/scripts/',
    fetchImpl: fileFetch,
    langBase: 'http://local/assets/lang/',
    wasmFile: join(here, 'node_modules', 'wasmoon', 'dist', 'glue.wasm'),
    // These DOM/text flows have no AudioContext. Their explicit test-project
    // declaration allows silent continuation and accepts the existing CSS tint.
    // Audio playback and required-feature rejection have separate real routes.
    capabilities: JSON.parse(readFileSync(join(rootDir, 'demo/caesura.project.json'), 'utf8')).capabilities,
  })
  stage = document.createElement('div')
  document.body.appendChild(stage)
  renderer = new DomRenderer(player.core, stage)
})

describe('browser flow (jsdom + wasmoon + DOM)', () => {
  it('renders the scene into DOM and advances on clicks', async () => {
    const ks = readFileSync(join(here, '..', 'demo', 'galgame_demo.ks'), 'utf8')
    let out = await player.runScene(ks, 'galgame_demo.ks', { maxFrames: 50000 })
    expect(out.startsWith('WAIT:')).toBe(true)
    for (const [id, t] of player.core.textures) {
      renderer.setTextureUrl(id, '/assets/' + t.path)
    }
    renderer.render()

    const bgImg = stage.querySelector('img[data-layer="bg"]')
    expect(bgImg).toBeTruthy()
    expect(bgImg.getAttribute('src')).toContain('classroom.png')
    const msg = stage.querySelector('.caesura-message')
    expect(msg?.textContent).toContain('Welcome to Caesura')
    // structured draws render as positioned spans (x/y/color/scale)
    const spans = msg?.querySelectorAll('span')
    expect(spans && spans.length).toBeGreaterThan(0)
    expect(spans[0].style.left).toBeTruthy()
    expect(spans[0].style.top).toBeTruthy()
    expect(spans[0].style.color).toMatch(/rgb\(/)
    expect(spans[0].style.fontSize).toMatch(/px/)
    // layer transitions: CSS animates engine-driven moves/fades
    const bgEl = stage.querySelector('img[data-layer="bg"]')
    expect(bgEl.style.transition).toContain('left 300ms')
    expect(bgEl.style.opacity).toBe('1') // 255 -> 1.0 normalized

    out = await player.runScene(ks, 'galgame_demo.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:')).toBe(true)
    // map any textures the second run loaded (hana.png got a new id)
    for (const [id, t] of player.core.textures) {
      renderer.setTextureUrl(id, '/assets/' + t.path)
    }
    await renderer.render()

    const bg2 = stage.querySelector('img[data-layer="bg"]')
    expect(bg2).toBeTruthy()
    expect(bg2.getAttribute('src')).toContain('hana.png')
    expect(stage.querySelector('img[data-layer="_char_Sakura"]')).toBeTruthy()
    expect(stage.querySelector('img[data-layer="_char_Teacher"]')).toBeTruthy()
    // after the final [p] the message layer is cleared (engine semantics)
    const msg2 = stage.querySelector('.caesura-message')
    expect(msg2).toBeNull()

    // sprite_move animated _char_Sakura toward 120,200 (a later [ch sprite=]
    // re-centers the layer at 440 — engine semantics; assert the move ran
    // and the CSS transition is armed).
    const sakura = stage.querySelector('img[data-layer="_char_Sakura"]')
    expect(sakura).toBeTruthy()
    const sakMoves = player.core.events.filter((e) => e.kind === 'layer.move' && e.detail.name === '_char_Sakura')
    expect(sakMoves.length).toBeGreaterThan(20) // full sprite_move animation
    expect(sakMoves[sakMoves.length - 1].detail.x).toBe(120)
    expect(sakura.style.transition).toContain('left 300ms')
  }, 120000)

  it('executes a freshly baked current .ksc stream without source parsing', async () => {
    const ksc = await player.lua.doString(`
      local compiler = require('kag.compiler')
      local tokens = compiler.compile_from_source('[set var="f.cache_only" value=7]\\n[ch text="Cached scene"]\\n[end]', 'cached.ks')
      return 'return '..compiler.encode_lua_literal(assert(compiler.serialize(tokens)))
    `)
    player.lua.global.set('KSC_SRC', ksc)
    const data = await player.lua.doString("return assert(load(KSC_SRC, '@cached.ksc', 't', {}))()")
    expect(data.version).toBe(2)
    expect(data.tokens.length).toBeGreaterThan(0)
    expect(data.labels).toBeTruthy()
    await player.lua.doString(`
      local tokenizer, compiler = require('tokenizer'), require('kag.compiler')
      local parse, compile = tokenizer.parse, compiler.compile
      __U14_RESTORE_CACHE_PROBE = function()
        tokenizer.parse, compiler.compile = parse, compile
      end
      tokenizer.parse = function() error('cached execution attempted source parsing') end
      compiler.compile = function(tokens)
        assert(tokens._compiled, 'cached execution attempted fresh compilation')
        return compile(tokens)
      end
    `)
    try {
      const result = await player.runFromBundle({ version: 1, scenes: { 'cached.ks': data }, assets: [] },
        'cached.ks', { maxFrames: 1000, autoClick: true })
      expect(result, 'the decoded current cache must execute').toMatch(/^DONE:/)
      expect(await player.lua.doString("return require('kag_runner').get_ctx().f.cache_only")).toBe(7)
      expect(player.core.backlog.map(page => page.text ?? '').join(' ')).toContain('Cached scene')
    } finally {
      await player.lua.doString('__U14_RESTORE_CACHE_PROBE(); __U14_RESTORE_CACHE_PROBE=nil')
    }
  }, 60000)

  // Sprint 1 / t3: the story-bundle load path is verified in two tiers.
  //   Tier 1 (always runs, no build artifact): bake a bundle in-process from a
  //   real demo .ks through kag.compiler and drive the SAME load chain
  //   main.mjs uses (load(STORY_SRC) -> chunk() -> { version, scenes, assets }).
  //   Tier 2 (skipped with a visible reason when the artifact is absent):
  //   the real ks_bake --web output on disk.
  // The old single case bailed out with a bare `return` when the artifact was
  // missing, which vitest reports as PASSED — a missing bundle (= the bake
  // step never ran or failed) produced a green, assertion-free result.
  it('loads a story bundle built in-process (no build artifact required)', async () => {
    const ks = readFileSync(join(here, '..', 'demo', 'galgame_demo.ks'), 'utf8')
    player.lua.global.set('KS_FOR_STORY', ks)
    // Same encoder ks_bake --web uses (compiler.encode_lua_literal), so the
    // literal below is byte-shaped like a real bundle scene entry.
    const sceneLiteral = await player.lua.doString([
      "  local tokenizer = require('tokenizer')",
      "  local compiler = require('kag.compiler')",
      '  local tokens = tokenizer.parse(KS_FOR_STORY)',
      '  compiler.compile(tokens)',
      '  return compiler.encode_lua_literal(compiler.serialize(tokens))',
    ].join(String.fromCharCode(10)))
    expect(typeof sceneLiteral).toBe('string')
    expect(sceneLiteral.length).toBeGreaterThan(100)
    const story = 'return { version = 1, scenes = { ["galgame_demo.ks"] = '
      + sceneLiteral + ' }, assets = { "assets/bg/classroom.png" } }'
    player.lua.global.set('STORY_SRC', story)
    const bundle = await player.lua.doString([
      '  local chunk = assert(load(STORY_SRC, \'@story.lua\', \'t\', _ENV))',
      '  return chunk()',
    ].join(String.fromCharCode(10)))
    expect(bundle.version).toBe(1)
    expect(bundle.scenes).toBeTruthy()
    expect(bundle.scenes['galgame_demo.ks']).toBeTruthy()
    expect(bundle.assets.length).toBeGreaterThan(0)
    expect(bundle.assets.some((a) => a.includes('classroom.png'))).toBe(true)
  }, 60000)

  it.skipIf(!hasBakedStory)(
    'loads the ks_bake --web story bundle from disk (scenes + assets) [requires: ' + BAKE_CMD + ']',
    async () => {
      const story = readFileSync(bakedStoryPath, 'utf8')
      player.lua.global.set('STORY_SRC', story)
      const bundle = await player.lua.doString([
        '  local chunk = assert(load(STORY_SRC, \'@story.lua\', \'t\', _ENV))',
        '  return chunk()',
      ].join(String.fromCharCode(10)))
      expect(bundle.version).toBe(1)
      expect(bundle.scenes).toBeTruthy()
      expect(bundle.scenes['galgame_demo.ks']).toBeTruthy()
      expect(bundle.assets.length).toBeGreaterThan(0)
      expect(bundle.assets.some((a) => a.includes('classroom.png'))).toBe(true)
    },
    60000,
  )

  it('runFromBundle executes a baked scene via the Lua-literal bridge (round 89 fix)', async () => {
    // Regression: runFromBundle used to hand JS objects to wasmoon via
    // global.set, which arrives as a *userdata* proxy; compiler.deserialize
    // strictly requires a Lua table, so every bundled scene instantly
    // 'DONE:1:0' without executing. The bridge now encodes the scenes map
    // as a Lua literal and rebuilds real tables on the Lua side.
    const ks = [
      '*start',
      "[ch name='Hero' text='bundle hello']",
      '[p]',
      "[ch name='Hero' text='bundle end']",
      '[end]',
    ].join('\n')
    player.lua.global.set('KS_FOR_BAKE', ks)
    const bundle = await player.lua.doString([
      "local tokenizer = require('tokenizer')",
      "local compiler = require('kag.compiler')",
      'local tokens = tokenizer.parse(KS_FOR_BAKE)',
      'compiler.compile(tokens)',
      'local stream = compiler.serialize(tokens)',
      'return { version = 1, scenes = { baked_one_ks = stream }, assets = {} }',
    ].join(String.fromCharCode(10)))
    expect(bundle.scenes.baked_one_ks).toBeTruthy()
    player.core.events.length = 0
    player.core.backlog.length = 0
    const out = await player.runFromBundle(bundle, 'baked_one_ks', { maxFrames: 5000, autoClick: true })
    expect(out.startsWith('DONE:'), 'bundle scene should complete: ' + out).toBe(true)
    expect(out, 'bundle scene should execute past token 1').not.toBe('DONE:1:0')
    // text lands in the backlog pages (bundle path commits [p] pages the
    // same way the source path does)
    const texts = player.core.backlog.flatMap((pg) =>
      Array.isArray(pg.draws) ? pg.draws.map((d) => d.t || '') : [])
    expect(texts.some((x) => x.includes('bundle hello'))).toBe(true)
    expect(texts.some((x) => x.includes('bundle end'))).toBe(true)
  }, 60000)


  // round 79: parameterized regression sweep — the REAL demo teaching files
  // (01-13) + showcase.ks run through the wasmoon player to completion with
  // ZERO unexpected error events; cheap per-file end states are asserted so a
  // regression in any tutorial surfaces the exact file. example_game's story
  // is included too (auto-click drives its [sel] choices down route 1 -> good end).
  const tutorialSweep = [
    ['tutorial_01_hello.ks', 'tutorial', /你好，世界/, [], {}],
    ['tutorial_02_text.ks', 'tutorial', /文本命令学完了/, [], {}],
    ['tutorial_03_layers.ks', 'tutorial', /图层教程完成/, [], {}],
    ['tutorial_04_audio.ks', 'tutorial', /音频教程完成/, [], { skipped: ['audio.play', 'audio.fade', 'audio.crossfade'] }],
    // branching converges at *ending regardless of the random coin; exactly
    // one of 路线 A / 路线 B may render (f.luck = math.random(2)).
    ['tutorial_05_branching.ks', 'tutorial', /分支教学完成/, [], { pathA: /路线 A/, pathB: /路线 B/ }],
    ['tutorial_06_effects.ks', 'tutorial', /教程 06 完成/, [], {}],
    // round 45: save/load + system-UI stubs degrade gracefully (no error)
    ['tutorial_07_saveload.ks', 'tutorial', /存档教程完成/, [], {}],
    ['tutorial_08_system_ui.ks', 'tutorial', /教程 08 完成/, [], {}],
    ['tutorial_09_interpolation.ks', 'tutorial', /插值教程完成/, [], {}],
    ['tutorial_10_loops.ks', 'tutorial', /循环教程完成/, [], {}],
    ['tutorial_11_switch.ks', 'tutorial', /switch 教程完成/, [], {}],
    ['tutorial_12_expr_combo.ks', 'tutorial', /表达式组合教程完成/, [], {}],
    // round 71/77: [palette day/night/toggle] must fire REAL palette.set events
    ['tutorial_13_commands.ks', 'tutorial', /KAG3 兼容命令教程完成/, [], { palette: 3 }],
    // round 87/88 flow&timing: [wait]/[delay] with stop_flag alignment,
    // [goto]/[jump] mixing + loop-stack reset, [i18n] plural dictionary values
    ['tutorial_14_flow_timing.ks', 'tutorial', /计时与流程教程完成/, [], {}],
    // round 84 advanced expression: nested ternary, multi-param comma-segment
    // function calls, ?? null-coalesce, [eval] ternary assignment
    ['tutorial_15_expr_deep.ks', 'tutorial', /高级表达式教程完成/, [], {}],
    ['showcase.ks', '', null, 'Thanks for watching the showcase.', {}],
    // auto-click resolves both [sel] blocks to option 1 -> good ending
    ['story.ks', 'example_game', null, 'Thank you for playing. / 感谢游玩。',
      { skipped: ['audio.play', 'render.postfx.vignette', 'render.postfx.bloom', 'render.particles'] }],
  ]
  it.each(tutorialSweep)('%s completes with zero unexpected error events', async (file, dir, teaching, terminal, flags) => {
    const sub = dir ? dir + '/' : ''
    const ks = readFileSync(join(here, '..', 'demo', sub, file), 'utf8')
    player.core.events.length = 0
    player.core.backlog.length = 0
    const out = await player.runScene(ks, file, { maxFrames: 300000, autoClick: true })
    // scene must reach [end] (never a frame-limit abort or parked [p])
    expect(out.startsWith('DONE:'), file + ' should complete: ' + out).toBe(true)
    // zero unexpected error events surfaced through the runner
    const errs = player.core.events.filter((e) => String(e.kind).includes('error'))
    expect(errs, file + ' should have no error events').toEqual([])
    if (flags.skipped) {
      const diagnostics = await player.lua.doString("return require('kag_runner').get_ctx().capability_diagnostics")
      for (const feature of flags.skipped) {
        expect(Object.values(diagnostics).some(result => result.feature === feature && result.status === 'unsupported')).toBe(true)
      }
      expect(player.audio.isPlaying('bgm')).toBe(false)
    }
    // teaching lines (tutorials) flow through the text.update / backlog draws
    if (teaching) {
      const texts = player.core.events
        .filter((e) => e.kind === 'text.draws')
        .flatMap((e) => (Array.isArray(e.detail?.draws) ? e.detail.draws : []))
        .map((d) => d.t || '')
        .concat(player.core.backlog.flatMap((p) => p.draws.map((d) => d.t || '')))
      expect(texts.some((x) => teaching.test(x)), file + ' should contain teaching line').toBe(true)
    }
    const backlog = player.core.backlog.map((b) => b.text || b.src || '').join(' | ')
    const draws = player.core.events.filter((e) => e.kind === 'text.draws').flatMap((e) => (Array.isArray(e.detail?.draws) ? e.detail.draws : [])).map((d) => d.t || '')
    const all = (backlog + ' | ' + draws.join(' | '))
    // per-file end states
    if (flags.pathA && flags.pathB) {
      // tutorial_05 branching: exactly one of the two coin paths renders
      expect(flags.pathA.test(all) ? 1 : (flags.pathB.test(all) ? 1 : 0), file + ' should reach A or B').toBe(1)
      expect(flags.pathA.test(all) === flags.pathB.test(all), file + ' picks exactly one branch').toBe(false)
    }
    if (typeof flags.palette === 'number') {
      const pal = player.core.events.filter((e) => e.kind === 'palette.set').length
      expect(pal === flags.palette, file + ' should fire ' + flags.palette + ' palette.set events, got ' + pal).toBe(true)
    }
    if (terminal) {
      expect(all.includes(terminal), file + ' should show terminal line: ' + terminal).toBe(true)
    }
  }, 120000)
  it('persists saves across scenes (round 46 web save bridge)', async () => {
    // isolate: fresh keys so earlier tests cannot leak state
    for (const k of [...Object.keys(localStorage)]) if (k.startsWith('caesura.save.')) localStorage.removeItem(k)
    const NL = String.fromCharCode(10)
    const saveKs = [
      '[set f.coins = 100]',
      '[set f.name = "樱"]',
      '[save slot=1]',
      '[end]',
    ].join(NL)
    const out1 = await player.runScene(saveKs, 'savegame.ks', { maxFrames: 200000, autoClick: true })
    expect(out1.startsWith('DONE:')).toBe(true)
    expect(player.core.events.some((e) => e.kind === 'save.write')).toBe(true)

    // fresh run loads slot 1 and restores variables (load sets stop_flag,
    // so the scene halts after restoring — engine semantics)
    const loadKs = [
      '[ch name="N" text="before"]',
      '[p]',
      '[load slot=1]',
      '[end]',
    ].join(NL)
    player.core.events.length = 0
    const out2 = await player.runScene(loadKs, 'loadgame.ks', {
      maxFrames: 200000, autoClick: true, sceneSources: { 'savegame.ks': saveKs },
    })
    expect(out2.startsWith('DONE:')).toBe(true)
    expect(player.core.events.some((e) => e.kind === 'save.read')).toBe(true)
    // [load] succeeded: engine logged Loaded slot 1 (no error events)
    const errs = player.core.events.filter((e) => String(e.kind).includes('error'))
    expect(errs.length).toBe(0)
  }, 120000)

  it('resumes from the saved point after [load] (round 47)', async () => {
    for (const k of [...Object.keys(localStorage)]) if (k.startsWith('caesura.save.')) localStorage.removeItem(k)
    const NL = String.fromCharCode(10)
    // Scene A saves mid-way; the loader scene then [load]s it and the
    // player must continue from the saved token (engine resume semantics).
    const sceneA = [
      '[ch name="N" text="A1"]',
      '[p]',
      '[ch name="N" text="A2"]',
      '[p]',
      '[set f.marker = 42]',
      '[save slot=1]',
      '[ch name="N" text="A3 after save"]',
      '[p]',
      '[ch name="N" text="A4"]',
      '[p]',
      '[end]',
    ].join(NL)
    await player.runScene(sceneA, 'scene_a.ks', { maxFrames: 200000, autoClick: true })
    const loader = [
      '[ch name="N" text="LOADER-START"]',
      '[p]',
      '[load slot=1]',
      '[end]',
    ].join(NL)
    player.core.backlog.length = 0
    const out = await player.runScene(loader, 'loader.ks', {
      maxFrames: 200000, autoClick: true,
      sceneSources: { 'scene_a.ks': sceneA },
    })
    expect(out.startsWith('DONE:')).toBe(true)
    // Restore replaces future loader history with the saved game's history.
    const texts = player.core.backlog.map((x) => x.text).join(' | ')
    expect(texts).not.toContain('LOADER-START')
    expect(texts).toContain('A3 after save')
    expect(texts).toContain('A4')
  }, 120000)

  it('manages save slots: list/save-current/delete (round 49)', async () => {
    for (const k of [...Object.keys(localStorage)]) if (k.startsWith('caesura.save.')) localStorage.removeItem(k)
    const NL = String.fromCharCode(10)
    const sceneA = [
      '[ch name="N" text="S1"]',
      '[p]',
      '[ch name="N" text="S2"]',
      '[p]',
      '[save slot=1]',
      '[ch name="N" text="S3"]',
      '[p]',
      '[end]',
    ].join(NL)
    await player.runScene(sceneA, 'scene_a.ks', { maxFrames: 200000, autoClick: true })

    // listSlots reflects the [save] made inside the scene
    let slots = player.listSlots()
    expect(slots.some((s) => s.slot === 1 && s.scene.includes('scene_a.ks'))).toBe(true)

    // saveCurrent captures the LAST run's position into another slot
    const ok = await player.saveCurrent(9)
    expect(ok).toBe(true)
    slots = player.listSlots()
    const s9 = slots.find((s) => s.slot === 9)
    expect(s9).toBeTruthy()
    expect(s9.token).toBeGreaterThan(1)

    // deleteSlot removes and is idempotent
    expect(player.deleteSlot(1)).toBe(true)
    expect(player.deleteSlot(1)).toBe(false)
    expect(player.listSlots().some((s) => s.slot === 1)).toBe(false)
  }, 120000)

  it('loads a slot through the UI path and resumes (round 49)', async () => {
    for (const k of [...Object.keys(localStorage)]) if (k.startsWith('caesura.save.')) localStorage.removeItem(k)
    const NL = String.fromCharCode(10)
    const sceneA = [
      '[ch name="N" text="U1"]',
      '[p]',
      '[set f.tag = 7]',
      '[save slot=2]',
      '[ch name="N" text="U2 after save"]',
      '[p]',
      '[ch name="N" text="U3"]',
      '[p]',
      '[end]',
    ].join(NL)
    await player.runScene(sceneA, 'scene_a.ks', { maxFrames: 200000, autoClick: true })

    player.core.backlog.length = 0
    const out = await player.loadSlot(2, { sceneSources: { 'scene_a.ks': sceneA } })
    expect(out.startsWith('DONE:')).toBe(true)
    const texts = player.core.backlog.map((x) => x.text).join(' | ')
    expect(texts).not.toContain('Loading slot 2')
    expect(texts).toContain('U2 after save')
    expect(texts).toContain('U3')
  }, 120000)

  it('runs the showcase sample (25 commands, branching, backlog)', async () => {
    player.core.backlog.length = 0 // isolate from earlier scenes
    const ks = readFileSync(join(here, '..', 'demo', 'showcase.ks'), 'utf8')
    const out = await player.runScene(ks, 'showcase.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:')).toBe(true)
    // branching took the lucky path; [ending] unlocked the showcase ending
    const ending = player.core.events.some((e) => e.kind === 'ending.unlock')
    // backlog accumulated per [p] page
    expect(player.core.backlog.length).toBeGreaterThan(5)
    expect(player.core.backlog[0].text).toContain('Welcome to the Caesura')
  }, 120000)

  it('exercises round 53-63 expression edges in the web player', async () => {
    player.core.backlog.length = 0
    // Ternary-in-index, ?? null-coalesce, long-bracket interpolation,
    // [switch exp=], [eval] TJS operators and expression-bound [for] —
    // the desktop fixes must behave identically under wasmoon.
    const ks = [
      '[set f.flag = true]',
      '[set f.hp = 30]',
      '[eval exp="f.arr = {10, 20}"]',
      '[eval exp="f.ok = f.hp > 10 && f.flag"]',
      '[ch name="N" text="idx=\x24{f.arr[f.flag ? 1 : 2]}"]',
      '[p]',
      '[set f.flag = false]',
      '[ch name="N" text="idx2=\x24{f.arr[f.flag ? 1 : 2]}"]',
      '[p]',
      '[ch name="N" text="nc=\x24{f.missing ?? 42}"]',
      '[p]',
      '[ch name="N" text="lb=\x24{ [[x}}]] .. \'A\' }"]',
      '[p]',
      '[ch name="N" text="ok=\x24{f.ok}"]',
      '[p]',
      '[set f.tier = 2]',
      '[switch exp="f.tier"]',
      '[case 1]',
      '[ch name="N" text="tier-one"]',
      '[case 2]',
      '[ch name="N" text="tier-two"]',
      '[endswitch]',
      '[ch name="N" text="sw=done"]',
      '[p]',
      '[set f.n = 2]',
      '[for var="i" start="1" end="f.n"]',
      '[ch name="N" text="loop\x24{f.i}"]',
      '[endfor]',
      '[ch name="N" text="expr-edge-done"]',
      '[p]',
      '[end]',
    ].join('\n')
    const out = await player.runScene(ks, 'expr_edge.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    const texts = player.core.backlog.map((x) => x.text).join(' | ')
    expect(texts).toContain('idx=10')          // ternary-in-index then-branch
    expect(texts).toContain('idx2=20')         // ternary-in-index else-branch
    expect(texts).toContain('nc=42')           // ?? fallback on missing var
    expect(texts).toContain('lb=x}}A')         // long-bracket braces survive
    expect(texts).toContain('ok=true')         // [eval] && translation
    expect(texts).toContain('tier-two')        // [switch exp=] numeric match
    expect(texts).toContain('sw=done')         // flow continues after switch
    expect(texts).toContain('loop1')           // [for] expression end bound
    expect(texts).toContain('loop2')
    expect(texts).toContain('expr-edge-done')
  }, 120000)
  it('[for] loop exposes its counter in f and accumulates via [add] (round 74/75)', async () => {
    player.core.backlog.length = 0
    const NL = String.fromCharCode(10)
    const ks = [
      '[set f.sum = 0]',
      '[for var="i" start="1" end="3"]',
      '[add name="f.sum" value=1]',
      '[endfor]',
      '[ch name="N" text="sum=\x24{f.sum} after=\x24{f.i}"]',
      '[p]',
      '[end]',
    ].join(NL)
    const out = await player.runScene(ks, 'loop_edge.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    const texts = player.core.backlog.map((b) => b.text).join(' | ')
    // body executed once per bound range step: [add] accumulated 1+1+1=3
    expect(texts).toContain('sum=3')
    // the loop counter is exposed in the f table and left past the bound
    expect(texts).toContain('after=4')
  }, 120000)

  it('[sel x="tf.result"]/[endbutton] writes the chosen target label (round 74/75)', async () => {
    player.core.backlog.length = 0
    const NL = String.fromCharCode(10)
    // auto-click selects option 1; the choice routes to its *label.
    const ks = [
      '[sel x="tf.result" target="*route_a" text="Route A"]',
      '[sel x="tf.result" target="*route_b" text="Route B"]',
      '[endbutton]',
      '[end]',
      '*route_a',
      '[ch name="N" text="chose-a=\x24{tf.result}"]',
      '[p]',
      '[end]',
    ].join(NL)
    const out = await player.runScene(ks, 'choice_a.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    expect(player.core.backlog.map((b) => b.text).join(' | ')).toContain('chose-a=*route_a')

    // choiceIndex=2 picks the second option -> routes to *route_b
    player.core.backlog.length = 0
    const ks2 = [
      '[sel x="tf.result" target="*route_a" text="Route A"]',
      '[sel x="tf.result" target="*route_b" text="Route B"]',
      '[endbutton]',
      '[end]',
      '*route_b',
      '[ch name="N" text="chose-b=\x24{tf.result}"]',
      '[p]',
      '[end]',
    ].join(NL)
    const out2 = await player.runScene(ks2, 'choice_b.ks', {
      maxFrames: 200000, autoClick: true, choiceIndex: 2,
    })
    expect(out2.startsWith('DONE:'), out2).toBe(true)
    expect(player.core.backlog.map((b) => b.text).join(' | ')).toContain('chose-b=*route_b')
  }, 120000)

  it('[ruby] follows the text cursor when no x/y is given (round 74)', async () => {
    player.core.draws = []
    const NL = String.fromCharCode(10)
    const ks = [
      '[ch name="N" text="GO"]',
      '[ruby text="漢字" ruby="かんじ"]',
      '[end]',
    ].join(NL)
    const out = await player.runScene(ks, 'ruby_follow.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    // the bare [ruby] (no x/y) lands on the current text cursor, NOT the
    // absolute (0,0) that schema.coerce's x=0/y=0 defaults used to pin — the
    // round-74 fix. core.draws carries the base text at its computed x/y.
    const rubyDraw = player.core.draws.find((d) => d.t === '漢字')
    expect(rubyDraw).toBeTruthy()
    expect(rubyDraw.x).toBeGreaterThan(0)
    expect(rubyDraw.y).toBeGreaterThan(0)
    // specifically it matches the message window cursor (after the GO line),
    // i.e. it followed the cursor rather than pinning to the origin.
    expect(rubyDraw.y).toBeGreaterThan(100)
  }, 120000)

  it('[nvl on]/[nvl off] toggles _textbox/_nameplate layer visibility (round 74)', async () => {
    player.core.layers.clear()
    const NL = String.fromCharCode(10)
    // [textbox] creates _textbox; [ch name=...] renders the _nameplate.
    const ks = [
      '[textbox x=0 y=520 w=1280 h=200 color="0,0,0" opacity=200]',
      '[nameplate y=480 w=220 h=36 color="0,0,0"]',
      '[ch name="N" text="pre"]',
      '[p]',
      '[nvl on]',
      '[set f.mark = 1]',
      '[end]',
    ].join(NL)
    const out = await player.runScene(ks, 'nvl_hide.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    // [nvl on] hides the fixed message window + nameplate (Ren'Py NVL parity)
    expect(player.core.getLayer('_textbox').visible).toBe(false)
    expect(player.core.getLayer('_nameplate').visible).toBe(false)

    // fresh run: [nvl off] restores the pre-NVL visibility
    player.core.layers.clear()
    const ks2 = [
      '[textbox x=0 y=520 w=1280 h=200 color="0,0,0" opacity=200]',
      '[nameplate y=480 w=220 h=36 color="0,0,0"]',
      '[ch name="N" text="pre"]',
      '[p]',
      '[nvl on]',
      '[nvl off]',
      '[set f.mark2 = 1]',
      '[end]',
    ].join(NL)
    const out2 = await player.runScene(ks2, 'nvl_restore.ks', { maxFrames: 200000, autoClick: true })
    expect(out2.startsWith('DONE:'), out2).toBe(true)
    expect(player.core.getLayer('_textbox').visible).toBe(true)
    expect(player.core.getLayer('_nameplate').visible).toBe(true)
  }, 120000)

  it('\x24{f.missing ?? fallback} null-coalescing interpolation (round 74/75)', async () => {
    player.core.backlog.length = 0
    const NL = String.fromCharCode(10)
    const ks = [
      '[set f.name = "fallback"]',
      '[ch name="N" text="nc=\x24{f.missing ?? f.name}"]',
      '[p]',
      '[set f.have = "present"]',
      '[ch name="N" text="hc=\x24{f.have ?? f.name}"]',
      '[p]',
      '[end]',
    ].join(NL)
    const out = await player.runScene(ks, 'interp_nc.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    const texts = player.core.backlog.map((b) => b.text).join(' | ')
    expect(texts).toContain('nc=fallback')  // missing key -> fallback var value
    expect(texts).toContain('hc=present')   // present key wins over fallback
  }, 120000)
  it('[while exp] loop iterates on web, bounded (round 76)', async () => {
    player.core.backlog.length = 0
    const NL = String.fromCharCode(10)
    // Data-driven [while]: counter + accumulator accumulate per iteration
    // and the loop terminates (bounded guard), mirroring the desktop run.
    const ks = [
      '[set f.counter = 0]',
      '[set f.sum = 0]',
      '[while exp="f.counter < 4"]',
      '[add name="f.counter" value=1]',
      '[add name="f.sum" value=1]',
      '[endwhile]',
      '[ch name="N" text="cnt=\x24{f.counter} sum=\x24{f.sum}"]',
      '[p]',
      '[end]',
    ].join(NL)
    const out = await player.runScene(ks, 'while_edge.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    const texts = player.core.backlog.map((b) => b.text).join(' | ')
    // body ran exactly 4 times (counter 0->4, sum 0->4), then the exp
    // turned false and the loop exited (no frame-limit error -> bounded).
    expect(texts).toContain('cnt=4')
    expect(texts).toContain('sum=4')
  }, 120000)

  it('[textspeed]/[cps] set ctx.text_speed (reveal pace) + ctx.cps (round 76)', async () => {
    const readCtx = async (name) => {
      await player.lua.doString('_G.__R = _G.__LAST_CTX and _G.__LAST_CTX[' + JSON.stringify(name) + '] or nil')
      return player.lua.global.get('__R')
    }
    // [textspeed cps=100] -> 100 chars/sec == 10 ms/char reveal pace
    await player.runScene('[textspeed cps=100]\n[end]', 'cps100.ks', { maxFrames: 200000, autoClick: true })
    expect(await readCtx('cps')).toBe(100)
    expect(await readCtx('text_speed')).toBe(10) // floor(1000/100)
    // [cps 25] (KAG3 bare alias) -> 25 chars/sec == 40 ms/char
    await player.runScene('[cps 25]\n[end]', 'cps25.ks', { maxFrames: 200000, autoClick: true })
    expect(await readCtx('cps')).toBe(25)
    expect(await readCtx('text_speed')).toBe(40) // floor(1000/25)
  }, 120000)

  it('[button cond="f.x..."] hides the false option on web (round 76)', async () => {
    player.core.backlog.length = 0
    const NL = String.fromCharCode(10)
    const ks = [
      '[set f.x = 1]',
      // cond false (1 > 1): "NeedX" must be filtered out at [endbutton]
      '[button text="NeedX" target="*high" cond="f.x > 1"]',
      // cond true (1 >= 1): only this option remains visible
      '[button text="Low" target="*low" cond="f.x >= 1"]',
      '[endbutton]',
      '[end]',
      '*low',
      '[ch name="N" text="picked-low"]',
      '[p]',
      '[end]',
      '*high',
      '[ch name="N" text="picked-high"]',
      '[p]',
      '[end]',
    ].join(NL)
    const out = await player.runScene(ks, 'cond_choice.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    const texts = player.core.backlog.map((b) => b.text).join(' | ')
    // auto-click picked the first VISIBLE option (Low) — the false cond
    // option was dropped, so the *high route never ran.
    expect(texts).toContain('picked-low')
    expect(texts).not.toContain('picked-high')

    // control: with f.x=5 both conds pass, so the first visible option is
    // "NeedX" (cond f.x > 1 true) -> routes to *high.
    player.core.backlog.length = 0
    const ks2 = [
      '[set f.x = 5]',
      '[button text="NeedX" target="*high" cond="f.x > 1"]',
      '[button text="Low" target="*low" cond="f.x >= 1"]',
      '[endbutton]',
      '[end]',
      '*low',
      '[ch name="N" text="picked-low"]',
      '[p]',
      '[end]',
      '*high',
      '[ch name="N" text="picked-high"]',
      '[p]',
      '[end]',
    ].join(NL)
    const out2 = await player.runScene(ks2, 'cond_choice2.ks', { maxFrames: 200000, autoClick: true })
    expect(out2.startsWith('DONE:'), out2).toBe(true)
    expect(player.core.backlog.map((b) => b.text).join(' | ')).toContain('picked-high')
  }, 120000)

  it('save inside a [for] body then [load] -> loop CONTINUES to completion (round 76)', async () => {
    for (const k of [...Object.keys(localStorage)]) if (k.startsWith('caesura.save.')) localStorage.removeItem(k)
    const NL = String.fromCharCode(10)
    // Save is taken mid-loop (2nd iteration). Round-75 desktop parity: the
    // web bridge saves through the REAL SaveCommands.save, whose
    // capture_state serializes ctx._forStack/_ifStack into loop_stacks; a
    // [load] restore writes ctx._resumeLoopStacks and the re-spawned
    // scheduler.run consumes it, so the for/if chain picks up where it
    // paused instead of silently ending.
    const sceneA = [
      '[set f.total = 0]',
      '[for var="i" start="1" end="3"]',
      '[add name="f.total" value=1]',
      '[if exp="f.i == 2"]',
      '[save slot=1]',
      '[endif]',
      '[endfor]',
      '[ch name="N" text="completed total=\x24{f.total} i=\x24{f.i}"]',
      '[p]',
      '[ch name="N" text="AFTER-LOOP-DONE"]',
      '[p]',
      '[end]',
    ].join(NL)
    await player.runScene(sceneA, 'loop_save.ks', { maxFrames: 200000, autoClick: true })
    const loader = [
      '[ch name="N" text="LOADER-START"]',
      '[p]',
      '[load slot=1]',
      '[end]',
    ].join(NL)
    player.core.backlog.length = 0
    const out = await player.runScene(loader, 'loader.ks', {
      maxFrames: 200000, autoClick: true,
      sceneSources: { 'loop_save.ks': sceneA },
    })
    expect(out.startsWith('DONE:'), out).toBe(true)
    const texts = player.core.backlog.map((x) => x.text).join(' | ')
    expect(texts).not.toContain('LOADER-START')
    // The loop body ran all 3 iterations (i=1 before save counts; save on
    // i=2, then iterations 2-finalize + 3 run after load), so total=3 and
    // the counter exited at i=4.
    expect(texts).toContain('completed total=3')
    expect(texts).toContain('i=4')
    expect(texts).toContain('AFTER-LOOP-DONE')
  }, 120000)

  it('[select]/[sel]/[endselect] KAG3 alias path works on web (round 76)', async () => {
    player.core.backlog.length = 0
    const NL = String.fromCharCode(10)
    // [select] opens the block (no-op), [sel x=] registers an option,
    // [endselect] renders + blocks (alias of [endbutton]). auto-click
    // selects option 1 -> routes to *route_p and records tf.result.
    const ks = [
      '[select]',
      '[sel x="tf.result" target="*route_p" text="PickP"]',
      '[sel x="tf.result" target="*route_q" text="PickQ"]',
      '[endselect]',
      '[end]',
      '*route_p',
      '[ch name="N" text="picked-p=\x24{tf.result}"]',
      '[p]',
      '[end]',
      '*route_q',
      '[ch name="N" text="picked-q"]',
      '[p]',
      '[end]',
    ].join(NL)
    const out = await player.runScene(ks, 'select_p.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    expect(player.core.backlog.map((b) => b.text).join(' | ')).toContain('picked-p=*route_p')

    // choiceIndex=2 picks the second option -> routes to *route_q
    player.core.backlog.length = 0
    const out2 = await player.runScene(ks, 'select_q.ks', {
      maxFrames: 200000, autoClick: true, choiceIndex: 2,
    })
    expect(out2.startsWith('DONE:'), out2).toBe(true)
    expect(player.core.backlog.map((b) => b.text).join(' | ')).toContain('picked-q')
  }, 120000)

  it('[goto] is a KAG3 alias of [jump] on web: skips intermediate text (round 76/77 parity)', async () => {
    player.core.backlog.length = 0
    const NL = String.fromCharCode(10)
    // Mirrors tests/scripts/test_scheduler.lua section 19: [goto *label] (and
    // target="*label") is the KAG3 intra-scene label alias of [jump], and
    // must skip the intermediate [ch] and land on the label. The scheduler
    // union handler runs the (real) Lua flow branch under wasmoon, so web
    // must match desktop.
    const ks = [
      '[ch name="N" text="A"]',
      '[goto *L1]',
      '[ch name="N" text="SKIPPED"]',
      '*L1',
      '[ch name="N" text="B"]',
      '[p]',
      '[end]',
    ].join(NL)
    const out = await player.runScene(ks, 'goto_label.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    const texts = player.core.backlog.map((b) => b.text).join(' | ')
    // A and B survive; the SKIPPED line between [goto] and the label never ran.
    expect(texts).toContain('A')
    expect(texts).toContain('B')
    expect(texts).not.toContain('SKIPPED')

    // named target="*L2" form (KAG3 alias path) also skips to the label
    player.core.backlog.length = 0
    const ks2 = [
      '[ch name="N" text="start"]',
      '[goto target="*L2"]',
      '[ch name="N" text="SKIP2"]',
      '*L2',
      '[ch name="N" text="end"]',
      '[p]',
      '[end]',
    ].join(NL)
    const out2 = await player.runScene(ks2, 'goto_target.ks', { maxFrames: 200000, autoClick: true })
    expect(out2.startsWith('DONE:'), out2).toBe(true)
    const t2 = player.core.backlog.map((b) => b.text).join(' | ')
    expect(t2).toContain('start')
    expect(t2).toContain('end')
    expect(t2).not.toContain('SKIP2')
  }, 120000)

  it('[i18n language="en"] hot-switch runs and records settingsValues.language (round 76/77 parity)', async () => {
    const readCtx = async (name) => {
      // same pattern as the [textspeed]/[cps] round-76 test: read a field
      // off __LAST_CTX (the exporter runs after every runScene).
      await player.lua.doString('_G.__R = _G.__LAST_CTX and _G.__LAST_CTX[' + JSON.stringify(name) + '] or nil')
      return player.lua.global.get('__R')
    }
    const NL = String.fromCharCode(10)
    const ks = [
      '[ch name="N" text="before"]',
      '[p]',
      '[i18n language="en"]',
      '[ch name="N" text="after"]',
      '[p]',
      '[end]',
    ].join(NL)
    const out = await player.runScene(ks, 'i18n_en.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    // no error events surfaced through the runner
    const errs = player.core.events.filter((e) => String(e.kind).includes('error'))
    expect(errs.length).toBe(0)
    // the [i18n] handler records the selected language on the scene ctx
    const sv = await readCtx('settingsValues')
    expect(sv).toBeTruthy()
    expect(sv.language).toBe('en')
    // the scene ran to completion after the switch (relocalize_page is a REAL
    // full-page redraw on web — the [i18n] handler drives it synchronously and
    // the bridge re-exports text_state.draws, so already-displayed lines here
    // carry the NEW language; see the round-78 relocalize tests below)
    expect(player.core.backlog.map((b) => b.text).join(' | ')).toContain('after')
  }, 120000)

  it('[i18n language] missing/empty param degrades gracefully on web (no crash)', async () => {
    const NL = String.fromCharCode(10)
    // The i18n command contract marks language= required=true, so
    // schema.coerce rejects a missing/empty param BEFORE the handler runs
    // (same as desktop: a controlled dispatch error, not a crash). The
    // graceful guarantee on web is that the player surfaces the error and
    // survives: the runtime is not torn down and a later valid scene runs.
    const bad = await player.runScene('[i18n]', 'i18n_missing.ks', { maxFrames: 200000, autoClick: true })
    expect(bad.startsWith('ERR:'), 'missing language should fail cleanly').toBe(true)
    expect(bad).toContain('missing required param')
    expect(bad).toContain('language')

    const badEmpty = await player.runScene('[i18n language=""]', 'i18n_empty.ks', { maxFrames: 200000, autoClick: true })
    expect(badEmpty.startsWith('ERR:')).toBe(true)

    // Post-error robustness: a valid [i18n language="en"] still runs and
    // records the language (the rejected dispatch did not corrupt the VM).
    const good = ['[ch name="N" text="ok"]', '[p]', '[i18n language="ja"]', '[ch name="N" text="after"]', '[p]', '[end]'].join(NL)
    const out = await player.runScene(good, 'i18n_recover.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    await player.lua.doString('_G.__R = _G.__LAST_CTX and _G.__LAST_CTX.settingsValues or nil')
    expect(player.lua.global.get('__R')).toBeTruthy()
    expect(player.lua.global.get('__R').language).toBe('ja')
    expect(player.core.backlog.map((b) => b.text).join(' | ')).toContain('after')
  }, 120000)

  // ---- round 78: settings-language hot-switch parity on web ----------------
  // Desktop's settings menu re-localizes the ALREADY-DISPLAYED page via
  // TextCommands.relocalize_page (replays text_state.page_src through
  // _drawMessage with the new dictionary). The web player loads the real
  // i18n.lua, so [i18n language=] -> SystemCommands.i18n drives the SAME
  // relocalize_page synchronously; the bridge re-exports text_state.draws
  // after every runScene, so the re-localized page, choice labels and
  // backlog are all observable from the harness. Zero web-side changes were
  // needed (the whole path is Lua-side + the existing draws exporter).

  it('[i18n] re-localizes the ALREADY-DISPLAYED page draws (round 78 relocalize)', async () => {
    const readCtx = async (name) => {
      await player.lua.doString('_G.__R = _G.__LAST_CTX and _G.__LAST_CTX[' + JSON.stringify(name) + '] or nil')
      return player.lua.global.get('__R')
    }
    const NL = String.fromCharCode(10)
    // Control in zh only: the same {settings} line renders as 设置.
    player.core.draws = []
    const zhKs = [
      '[i18n language="zh"]',
      '[ch name="N" text="v={settings}"]',
      '[end]',
    ].join(NL)
    await player.runScene(zhKs, 'rl_zh.ks', { maxFrames: 200000, autoClick: true })
    const zhT = player.core.draws.map((d) => d.t).join(' | ')
    expect(zhT).toContain('v=设置')

    // Hot-switch in the SAME scene: the [ch] renders in zh (设置), then
    // [i18n language="en"] re-localizes the already-displayed page to
    // Settings. Because relocalize_page REPLAYS the page source (it does not
    // append), the zh draw is replaced — v=设置 must be gone. (A non-NVL
    // [ch] clears the message window, so no display command follows the
    // switch here — that would refresh the page and drop the relocalized line.)
    player.core.draws = []
    const ks = [
      '[i18n language="zh"]',
      '[ch name="N" text="v={settings}"]',      // zh draw: "v=设置"
      '[i18n language="en"]',                   // relocalize_page -> "v=Settings"
      '[end]',
    ].join(NL)
    const out = await player.runScene(ks, 'rl_switch.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    const texts = player.core.draws.map((d) => d.t).join(' | ')
    // page draws were re-localized in place to the NEW (en) dictionary
    expect(texts).toContain('v=Settings')
    // and the old-language page draw was REPLAYED, not merely appended
    expect(texts).not.toContain('v=设置')
    // the switch recorded the active language on the scene ctx
    const sv = await readCtx('settingsValues')
    expect(sv && sv.language).toBe('en')

    // Persistence: a follow-up [ch] in the post-switch dictionary renders the
    // en value (the switch took effect for future lines, not just the redraw).
    player.core.draws = []
    const persist = [
      '[i18n language="en"]',
      '[ch name="N" text="post={language}"]',  // en draw: "post=Language"
      '[end]',
    ].join(NL)
    await player.runScene(persist, 'rl_persist.ks', { maxFrames: 200000, autoClick: true })
    expect(player.core.draws.map((d) => d.t).join(' | ')).toContain('post=Language')
  }, 120000)

  it('[button] choice labels registered pre-switch re-localize after [i18n] (round 78 relocalize)', async () => {
    const NL = String.fromCharCode(10)
    // A choice is STAGED in language A ([button text="{settings}"] -> 设置),
    // then [i18n language="en"] runs BEFORE [endbutton], so relocalize_page's
    // _relocalizeChoices rebuilds the label; [endbutton] then renders "1. Settings".
    // Park at the block (autoClick:false) so the rendered label is visible in
    // the exported draws (auto-selection would remove the choice group).
    player.core.draws = []
    const ks = [
      '[i18n language="zh"]',
      '[button text="{settings}" target="*a"]',
      '[i18n language="en"]',
      '[endbutton]',
      '[end]',
      '*a',
      '[ch name="N" text="arrived={language}"]',
      '[end]',
    ].join(NL)
    const out = await player.runScene(ks, 'rl_choice.ks', { maxFrames: 200000, autoClick: false })
    expect(out.startsWith('WAIT:'), out).toBe(true)
    const labels = player.core.draws.map((d) => d.t)
    // the rendered choice label shows the NEW language (en: "Settings")
    expect(labels.some((t) => t === '1. Settings'), JSON.stringify(labels)).toBe(true)
    // the old zh label was replaced, not left alongside
    expect(labels.some((t) => t === '1. 设置')).toBe(false)

    // A fresh run (auto-click picks option 1) routes through the relocalized
    // block and the post-switch dictionary persists for follow-up [ch].
    player.core.draws = []
    const out2 = await player.runScene(ks, 'rl_route.ks', { maxFrames: 200000, autoClick: true })
    expect(out2.startsWith('DONE:'), out2).toBe(true)
    const t2 = player.core.draws.map((d) => d.t).join(' | ')
    expect(t2).toContain('arrived=Language')
  }, 120000)

  it('[i18n] re-localizes ctx.backlog entries (round 78 relocalize, web runner exposes ctx)', async () => {
    const readBacklog = async () => {
      await player.lua.doString('_G.__R = _G.__LAST_CTX and _G.__LAST_CTX.backlog or nil')
      return player.lua.global.get('__R') || []
    }
    const NL = String.fromCharCode(10)
    // Control: pinned to zh, the backlog entry keeps its zh-localized text.
    const zhKs = [
      '[i18n language="zh"]',
      '[ch name="N" text="b={settings}"]',
      '[p]',
      '[end]',
    ].join(NL)
    player.core.backlog.length = 0
    await player.runScene(zhKs, 'rl_bk_zh.ks', { maxFrames: 200000, autoClick: true })
    const zhBl = await readBacklog()
    expect(zhBl.length).toBeGreaterThanOrEqual(1)
    expect(zhBl[0].text).toContain('b=设置')
    expect(zhBl[0].src).toBe('b={settings}')

    // Hot-switch scene: [ch] renders in zh, [p] commits the page, then
    // [i18n language="en"] -> relocalize_backlog re-localizes the stored
    // entry from its retained src (pre-localize source) to the new dict.
    const ks = [
      '[i18n language="zh"]',
      '[ch name="N" text="b={settings}"]',
      '[p]',
      '[i18n language="en"]',
      '[end]',
    ].join(NL)
    player.core.backlog.length = 0
    const out = await player.runScene(ks, 'rl_bk_switch.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    const bl = await readBacklog()
    expect(bl.length).toBeGreaterThanOrEqual(1)
    // entry was re-localized from 设置 -> Settings, keeping its src for the
    // next relocalize (the desktop backlog redraw contract).
    expect(bl[0].text).toContain('b=Settings')
    expect(bl[0].src).toBe('b={settings}')
  }, 120000)

  it('[palette] day/night/toggle apply the explicitly accepted CSS approximation', async () => {
    player.core.layers.clear()
    player.core.palette = { handle: null, intensity: 0, size: 0 }
    player.core.events.length = 0
    const NL = String.fromCharCode(10)
    // Minimal palette scene mirroring tutorial_13: day (clear) -> night
    // (load assets/lut/night.png + apply) -> toggle (back to day) -> day.
    // palette.lua drives the backend.* LUT surface; on web these are now
    // REAL bindings (load_image/is_valid/set_palette/destroy_texture) so
    // lut_available() is true and the scene runs WITHOUT the degrade.
    const ks = [
      '[palette effect=day]',
      '[palette effect=night]',
      '[palette effect=toggle]',
      '[palette effect=day]',
      '[ch name="N" text="palette-done"]',
      '[p]',
      '[end]',
    ].join(NL)
    const out = await player.runScene(ks, 'palette_lut.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    // No [palette] error: the old web gap crashed at palette.lua:39 (nil
    // load_image) and logged a KAG command 'palette' failed ERROR. A wired
    // LUT means zero error events.
    const errs = player.core.events.filter((e) => String(e.kind).includes('error'))
    expect(errs).toEqual([])
    // The engine's palette module tracked a real day<->night cycle:
    //   day -> set_palette(nil,0,0) neutral
    //   night -> load_image(path) => texture registered, set_palette(handle,1,16)
    //   toggle -> set_day_mode -> clear -> neutral
    //   day -> neutral again
    const sets = player.core.events.filter((e) => e.kind === 'palette.set')
    expect(sets.length).toBeGreaterThanOrEqual(4)
    // The night LUT was registered through the core texture pipeline.
    const nightTex = [...player.core.textures.values()].some((t) => t.path.includes('night.png'))
    expect(nightTex).toBe(true)
    // After the final [palette effect=day] the active LUT is cleared.
    expect(player.core.palette.handle).toBeNull()
  }, 120000)

  it('[palette] CSS approximation tints the DOM render output and clears on day', async () => {
    player.core.layers.clear()
    player.core.palette = { handle: null, intensity: 0, size: 0 }
    const NL = String.fromCharCode(10)
    // A background texture must be present so the render list is non-empty.
    const bgTex = player.core.loadTexture('bg_placeholder.png')
    player.core.layers.clear()
    const bg = player.core.ensureLayer('bg', { z: 0 })
    player.core.setLayerImage(bg, bgTex)
    renderer.setTextureUrl(bgTex, '/assets/bg_placeholder.png')
    // Neutral: no filter (day).
    player.core.setPalette(null, 0, 0)
    await renderer.render()
    expect(stage.style.filter).toBe('')
    // Night: the active palette tints the whole render output.
    player.core.setPalette(bgTex, 1.0, 16)
    await renderer.render()
    expect(stage.style.filter).toContain('brightness')
    expect(stage.style.filter).toContain('hue-rotate')
    // Back to day / neutral: filter clears.
    player.core.setPalette(null, 0, 0)
    await renderer.render()
    expect(stage.style.filter).toBe('')
  }, 60000)

  // -- round 81 resume: advance/skip/auto parity -------------------------
  // Desktop parity: each runScene(opts.advance) resumes the previously
  // parked scene cursor through the shared kag_runner on_click semantics.
  // An explicit [ch] followed by [p] has two independent input boundaries.
  const pageText = () => (player.core.draws || []).map((d) => d.t || '').join('')
  const advanceTextPage = async (source, name) => {
    const displayed = pageText()
    const opts = { maxFrames: 50000, advance: true, advanceScene: name }
    const atPageWait = await player.runScene(source, name, opts)
    expect(atPageWait.startsWith('WAIT:'), atPageWait).toBe(true)
    expect(pageText(), 'the explicit [p] retains the completed [ch] page').toBe(displayed)
    return player.runScene(source, name, opts)
  }

  it('advance resumes the parked scene one page at a time (round 81)', async () => {
    const NL = String.fromCharCode(10)
    const ks = [
      '[ch name="A" text="PAGE-ONE"]', '[p]',
      '[ch name="A" text="PAGE-TWO"]', '[p]',
      '[ch name="A" text="PAGE-THREE"]', '[p]',
      '[end]',
    ].join(NL)
    // Fresh start parks at the first [p].
    let out = await player.runScene(ks, 'adv_basic.ks', { maxFrames: 50000 })
    expect(out.startsWith('WAIT:')).toBe(true)
    expect(pageText()).toContain('PAGE-ONE')

    // Advance 1 -> ONE page forward, parked at the next [p] (PAGE-TWO shown).
    out = await advanceTextPage(ks, 'adv_basic.ks')
    expect(out.startsWith('WAIT:')).toBe(true)
    expect(pageText()).toContain('PAGE-TWO')
    expect(pageText()).not.toContain('PAGE-ONE')

    // Advance 2 -> PAGE-THREE.
    out = await advanceTextPage(ks, 'adv_basic.ks')
    expect(out.startsWith('WAIT:')).toBe(true)
    expect(pageText()).toContain('PAGE-THREE')

    // Advance 3 -> past the final [p], DONE.
    out = await advanceTextPage(ks, 'adv_basic.ks')
    expect(out.startsWith('DONE:')).toBe(true)
    // Backlog accumulated the departing pages (PAGE-ONE + PAGE-TWO + PAGE-THREE).
    const bl = (player.core.backlog || []).map((b) => b.text).join(' | ')
    expect(bl).toContain('PAGE-ONE')
    expect(bl).toContain('PAGE-TWO')
    expect(bl).toContain('PAGE-THREE')
  }, 120000)

  it('advance with a mismatched scene name restarts from token 1 (round 81)', async () => {
    const NL = String.fromCharCode(10)
    const ks = [
      '[ch name="A" text="PAGE-ONE"]', '[p]',
      '[ch name="A" text="PAGE-TWO"]', '[p]',
      '[end]',
    ].join(NL)
    let out = await player.runScene(ks, 'adv_mismatch.ks', { maxFrames: 50000 })
    expect(out.startsWith('WAIT:')).toBe(true)
    expect(pageText()).toContain('PAGE-ONE')

    // advanceScene does NOT match the current scene -> fresh run from token 1,
    // so we are parked at PAGE-ONE again (not advanced to PAGE-TWO).
    out = await player.runScene(ks, 'adv_mismatch.ks', { maxFrames: 50000, advance: true, advanceScene: 'some_other.ks' })
    expect(out.startsWith('WAIT:')).toBe(true)
    expect(pageText()).toContain('PAGE-ONE')
    expect(pageText()).not.toContain('PAGE-TWO')
  }, 120000)

  it('advance preserves [set] variables across pages (round 81)', async () => {
    const NL = String.fromCharCode(10)
    const ks = [
      '[set f.v = 10]',
      '[ch name="A" text="V1=${f.v}"]', '[p]',
      '[set f.v = 20]',
      '[ch name="A" text="V2=${f.v}"]', '[p]',
      '[end]',
    ].join(NL)
    const out0 = await player.runScene(ks, 'adv_vars.ks', { maxFrames: 50000 })
    expect(out0.startsWith('WAIT:')).toBe(true)
    expect(pageText()).toContain('V1=10')

    // Advancing must NOT wipe the ctx: [set f.v = 20] ran on the resumed
    // coroutine so V2 interpolates the variable that survived the advance.
    const out1 = await advanceTextPage(ks, 'adv_vars.ks')
    expect(out1.startsWith('WAIT:')).toBe(true)
    expect(pageText()).toContain('V2=20')

    const out2 = await advanceTextPage(ks, 'adv_vars.ks')
    expect(out2.startsWith('DONE:')).toBe(true)
  }, 120000)
  // -- round 78 i18n x round 81 advance combination -------------------------
  // Each [i18n] hot-switch (round 76/78) records ctx.settingsValues.language
  // and relocalizes the visible page/backlog/choices. Round-81 advance
  // resumes the SAME persistent ctx (__CTXREF) one [p] page at a time, so a
  // language switch that ran before a park survives the advance and steers
  // the freshly rendered page. These tests pin the two semantics together:
  // a page rendered after an advance must carry the language that was active
  // at the time its [i18n] line ran. No bridge changes were needed.

  it('[i18n] switch governs the page rendered by the NEXT advance (round 78 x 81)', async () => {
    const NL = String.fromCharCode(10)
    const pageT = () => (player.core.draws || []).map((d) => d.t || '').join('')
    player.core.draws = []
    const ks = [
      '[i18n language="zh"]',
      '[ch name="N" text="P1-{settings}"]', '[p]',
      '[i18n language="en"]',
      '[ch name="N" text="P2-{settings}"]', '[p]',
      '[i18n language="zh"]',
      '[ch name="N" text="P3-{settings}"]', '[p]',
      '[end]',
    ].join(NL)
    // Fresh park at the first [p]: page 1 renders in the initial zh dict.
    let out = await player.runScene(ks, 'i18n_adv.ks', { maxFrames: 50000 })
    expect(out.startsWith('WAIT:'), out).toBe(true)
    expect(pageT()).toContain('P1-设置')
    expect(pageT()).not.toContain('P1-Settings')

    // Advance 1 runs [i18n language="en"] then page 2 -> en dict.
    out = await advanceTextPage(ks, 'i18n_adv.ks')
    expect(out.startsWith('WAIT:'), out).toBe(true)
    expect(pageT()).toContain('P2-Settings')
    expect(pageT()).not.toContain('P2-设置')

    // Advance 2 switches back to zh -> page 3 renders in zh again.
    out = await advanceTextPage(ks, 'i18n_adv.ks')
    expect(out.startsWith('WAIT:'), out).toBe(true)
    expect(pageT()).toContain('P3-设置')
    expect(pageT()).not.toContain('P3-Settings')

    // Advance 3 -> past the last [p], DONE.
    out = await advanceTextPage(ks, 'i18n_adv.ks')
    expect(out.startsWith('DONE:'), out).toBe(true)
  }, 120000)

  it('language state survives advance and a fresh scene (i18n persistence, round 78 x 81)', async () => {
    const readCtx = async (name) => {
      await player.lua.doString('_G.__R = _G.__LAST_CTX and _G.__LAST_CTX[' + JSON.stringify(name) + '] or nil')
      return player.lua.global.get('__R')
    }
    const NL = String.fromCharCode(10)
    const pageT = () => (player.core.draws || []).map((d) => d.t || '').join('')
    const backlogT = () => (player.core.backlog || []).map((b) => b.text || '').join(' | ')
    player.core.draws = []
    player.core.backlog.length = 0
    const ks = [
      '[i18n language="en"]',
      '[ch name="N" text="E1-{settings}"]', '[p]',
      '[ch name="N" text="E2-{settings}"]', '[p]',   // no switch -> must stay en
      '[end]',
    ].join(NL)
    // Fresh: en selected and page 1 renders with it.
    let out = await player.runScene(ks, 'i18n_persist.ks', { maxFrames: 50000 })
    expect(out.startsWith('WAIT:'), out).toBe(true)
    expect(pageT()).toContain('E1-Settings')

    // Advance 1: NO i18n command between the pages; the en selection set
    // before the park must have survived the advance (round-81 keeps ctx).
    out = await advanceTextPage(ks, 'i18n_persist.ks')
    expect(out.startsWith('WAIT:'), out).toBe(true)
    expect(pageT()).toContain('E2-Settings')
    let sv = await readCtx('settingsValues')
    expect(sv && sv.language).toBe('en')

    // Advance 2 -> DONE; a later fresh scene (no [i18n]) still inherits en
    // because i18n.current outlives the scene (module-level state).
    out = await advanceTextPage(ks, 'i18n_persist.ks')
    expect(out.startsWith('DONE:'), out).toBe(true)

    player.core.draws = []
    player.core.backlog.length = 0
    const fresh = ['[ch name="N" text="F-{settings}"]', '[p]', '[end]'].join(NL)
    out = await player.runScene(fresh, 'i18n_persist_fresh.ks', { maxFrames: 50000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    // the fresh scene renders through the STILL-en dict: i18n.current outlives
    // both the advance chain and the scene boundary. (settingsValues is only
    // written by an [i18n] command, so the language check reads i18n.current.)
    expect(backlogT()).toContain('F-Settings')
    await player.lua.doString('_G.__R = (require("i18n")).current')
    expect(player.lua.global.get('__R')).toBe('en')
  }, 120000)

  it('[i18n] language persists through save/load (round 78 x storage semantics)', async () => {
    const readCtx = async (name) => {
      await player.lua.doString('_G.__R = _G.__LAST_CTX and _G.__LAST_CTX[' + JSON.stringify(name) + '] or nil')
      return player.lua.global.get('__R')
    }
    const NL = String.fromCharCode(10)
    const pageT = () => (player.core.draws || []).map((d) => d.t || '').join('')
    const backlogT = () => (player.core.backlog || []).map((b) => b.text || '').join(' | ')
    const slot = 77

    // Pin en, render one page, then save the current position. Save.save
    // persists state.language = settingsValues.language, so a reload must
    // hot-switch back to en (see save.lua restore).
    player.core.draws = []
    player.core.backlog.length = 0
    const enKs = [
      '[i18n language="en"]',
      '[ch name="N" text="SAVE-{settings}"]', '[p]',
      '[end]',
    ].join(NL)
    let out = await player.runScene(enKs, 'i18n_save.ks', { maxFrames: 50000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    // [p] commits the page, so the localized text sits in the backlog.
    expect(backlogT()).toContain('SAVE-Settings')
    expect(await player.saveCurrent(slot)).toBe(true)

    // Flip the running language to zh (separate scene) so a restore is visible.
    player.core.draws = []
    player.core.backlog.length = 0
    const zhKs = ['[i18n language="zh"]', '[ch name="N" text="NOW-{settings}"]', '[p]', '[end]'].join(NL)
    out = await player.runScene(zhKs, 'i18n_to_zh.ks', { maxFrames: 50000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    expect(backlogT()).toContain('NOW-设置')

    // Loading the save restores en (language + i18n.current hot-switch).
    player.core.draws = []
    player.core.backlog.length = 0
    out = await player.loadSlot(slot, {
      maxFrames: 50000, autoClick: true, sceneSources: { 'i18n_save.ks': enKs },
    })
    expect(out.startsWith('DONE:'), out).toBe(true)
    const sv = await readCtx('settingsValues')
    expect(sv && sv.language).toBe('en')

    // A follow-up [ch] in a fresh scene after the load renders with en again.
    player.core.draws = []
    player.core.backlog.length = 0
    const afterKs = ['[ch name="N" text="AFTER-{settings}"]', '[p]', '[end]'].join(NL)
    out = await player.runScene(afterKs, 'i18n_after_load.ks', { maxFrames: 50000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    expect(backlogT()).toContain('AFTER-Settings')

    player.deleteSlot(slot)
  }, 120000)

  it('backlog entries re-localize across advances (round 78 backlog + round 81 advance)', async () => {
    const readBacklog = async () => {
      await player.lua.doString('_G.__R = _G.__LAST_CTX and _G.__LAST_CTX.backlog or nil')
      return player.lua.global.get('__R') || []
    }
    const NL = String.fromCharCode(10)
    player.core.backlog.length = 0
    const ks = [
      '[i18n language="zh"]',
      '[ch name="N" text="b1={settings}"]', '[p]',
      '[i18n language="en"]',
      '[ch name="N" text="b2={settings}"]', '[p]',
      '[end]',
    ].join(NL)
    // Fresh park: page 1 (b1) is committed when we advance out of it.
    let out = await player.runScene(ks, 'i18n_bk_adv.ks', { maxFrames: 50000 })
    expect(out.startsWith('WAIT:'), out).toBe(true)

    // Advance 1: [i18n language="en"] commits b1 to backlog AND relocalizes
    // it (设置 -> Settings); page 2 renders b2 in en.
    out = await advanceTextPage(ks, 'i18n_bk_adv.ks')
    expect(out.startsWith('WAIT:'), out).toBe(true)

    // Advance 2 -> DONE; inspect the full backlog.
    out = await advanceTextPage(ks, 'i18n_bk_adv.ks')
    expect(out.startsWith('DONE:'), out).toBe(true)
    const bl = await readBacklog()
    const texts = bl.map((b) => b.text)
    // b1 committed under zh then relocalized to en on the switch.
    expect(bl.some((b) => b.text.includes('b1=Settings')), JSON.stringify(texts)).toBe(true)
    expect(bl.some((b) => b.text.includes('b1=设置')), JSON.stringify(texts)).toBe(false)
    // b2 committed under en directly.
    expect(bl.some((b) => b.text.includes('b2=Settings')), JSON.stringify(texts)).toBe(true)
    // entries keep their pre-localize src for the next relocalize.
    expect(bl.some((b) => b.src === 'b1={settings}' && b.text.includes('b1=Settings'))).toBe(true)
  }, 120000)

  it('i18n plural tables (round 80) hold their variant selection across advances', async () => {
    const setupPlural = async () => {
      await player.lua.doString([
        "local I = require('i18n')",
        "I.set_language('en')",
        "I.strings.items = { one = '{n} item', other = '{n} items' }",
      ].join(String.fromCharCode(10)))
    }
    const tNum = async (n) => {
      await player.lua.doString('_G.__R = (require("i18n")).translate("items", { n = ' + Number(n) + ' })')
      return player.lua.global.get('__R')
    }
    const NL = String.fromCharCode(10)
    await setupPlural()

    // Baseline: en plural picks one/other by count.
    expect(await tNum(1)).toBe('1 item')
    expect(await tNum(3)).toBe('3 items')

    // A real advancing scene runs against the live plural-active dict.
    player.core.draws = []
    const ks = ['[ch name="N" text="A1"]', '[p]', '[ch name="N" text="A2"]', '[p]', '[end]'].join(NL)
    let out = await player.runScene(ks, 'plural_adv.ks', { maxFrames: 50000 })
    expect(out.startsWith('WAIT:'), out).toBe(true)
    expect(await tNum(1)).toBe('1 item')
    expect(await tNum(5)).toBe('5 items')

    // After each advance the plural table (and en category) survive, so
    // variant selection still tracks the count.
    out = await advanceTextPage(ks, 'plural_adv.ks')
    expect(out.startsWith('WAIT:'), out).toBe(true)
    expect(await tNum(1)).toBe('1 item')
    expect(await tNum(2)).toBe('2 items')

    out = await advanceTextPage(ks, 'plural_adv.ks')
    expect(out.startsWith('DONE:'), out).toBe(true)
    expect(await tNum(0)).toBe('0 items')
    // zh/ja (and unknown) plural_category is always "other" regardless of n.
    await player.lua.doString('(require("i18n")).set_language("zh")')
    await player.lua.doString('(require("i18n")).strings.items = { other = "共 {n} 个", one = "一个" }')
    expect(await tNum(1)).toBe('共 1 个')
  }, 120000)

  // ---- round 82: [eval]/[random]/[ending]/backlog/[rollback]/vfx parity ---
  // Desktop behavior the web bridge had not yet pinned. The web player loads
  // the REAL scheduler.lua + kag command tables, so each of these must behave
  // identically under wasmoon (all verified against desktop semantics below).

  it('[eval exp=] bare expression stores tf.eval_result; assignment is a no-result statement (round 82 parity)', async () => {
    const readTF = async () => {
      await player.lua.doString('_G.__R = _G.__LAST_CTX and _G.__LAST_CTX.tf and _G.__LAST_CTX.tf.eval_result or nil')
      return player.lua.global.get('__R')
    }
    const NL = String.fromCharCode(10)
    // Bare arithmetic expression -> result 7 into tf.eval_result (the
    // scheduler wraps "return <expr>" through the full TJS pipeline).
    let out = await player.runScene(['[eval exp="1+2*3"]', '[end]'].join(NL), 'eval_arith.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    expect(await readTF()).toBe(7)

    // Bare ternary (TJS ? :) -> 1, proving the translateAssignment path.
    out = await player.runScene(['[set f.a = true]', '[eval exp="f.a ? 1 : 2"]', '[end]'].join(NL), 'eval_tern.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    expect(await readTF()).toBe(1)

    // Assignment compiles as a STATEMENT (result nil) -> f.hp set, and the
    // SAME scene's tf.eval_result stays at its earlier bare-expr value
    // (rawset fires only on result ~= nil). Both eval tags share one ctx,
    // because ctx.tf is per-scene (a fresh run re-creates it).
    out = await player.runScene(
      ['[eval exp="f.x = 1"]', '[eval exp="f.x * 2"]', '[eval exp="f.y = 99"]', '[end]'].join(NL),
      'eval_assign.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    await player.lua.doString('_G.__R = _G.__LAST_CTX and _G.__LAST_CTX.f and _G.__LAST_CTX.f.y or nil')
    expect(player.lua.global.get('__R')).toBe(99)
    // f.x * 2 stored 2 into eval_result; the f.y assignment (statement) did
    // not overwrite it.
    expect(await readTF()).toBe(2)
  }, 120000)

  it('[eval exp=] a runtime error degrades gracefully; the scene survives (round 82 parity)', async () => {
    const NL = String.fromCharCode(10)
    player.core.events.length = 0
    // [eval exp="error(42)"] raises inside the pcall'd eval; the scheduler
    // prints a diagnostic and CONTINUES (no scene abort — desktop behavior).
    const out = await player.runScene(
      ['[eval exp="error(42)"]', '[ch name="N" text="survived-eval-err"]', '[p]', '[end]'].join(NL),
      'eval_err.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    const texts = player.core.backlog.map((b) => b.text).join(' | ')
    expect(texts).toContain('survived-eval-err')
    // No error events surface through the runner (contained + printed).
    const errs = player.core.events.filter((e) => String(e.kind).includes('error'))
    expect(errs).toEqual([])
  }, 120000)

  it('[random var= min= max=] writes an integer in [min,max]; swaps inverted ranges (round 82 parity)', async () => {
    const readF = async (k) => {
      await player.lua.doString('_G.__R = _G.__LAST_CTX and _G.__LAST_CTX.f and _G.__LAST_CTX.f[' + JSON.stringify(k) + '] or nil')
      return player.lua.global.get('__R')
    }
    const NL = String.fromCharCode(10)
    player.core.events.length = 0
    // Bounded range: every draw is an integer in [1,6], and over 30 draws
    // more than one value appears (math.random is uniform, not constant).
    const draws = []
    for (let i = 0; i < 30; i++) {
      await player.runScene(['[random var="f.d" min=1 max=6]', '[end]'].join(NL), 'rand.ks', { maxFrames: 200000, autoClick: true })
      const v = await readF('d')
      expect(typeof v).toBe('number')
      expect(Number.isInteger(v)).toBe(true)
      expect(v).toBeGreaterThanOrEqual(1)
      expect(v).toBeLessThanOrEqual(6)
      draws.push(v)
    }
    expect(new Set(draws).size).toBeGreaterThan(1)
    // Inverted range min>max swaps (system.lua: min,max = max,min) -> still
    // a valid integer inside the swapped bounds, no error.
    const inv = await player.runScene(['[random var="f.r" min=9 max=2]', '[end]'].join(NL), 'rand_inv.ks', { maxFrames: 200000, autoClick: true })
    expect(inv.startsWith('DONE:'), inv).toBe(true)
    const iv = await readF('r')
    expect(Number.isInteger(iv)).toBe(true)
    expect(iv).toBeGreaterThanOrEqual(2)
    expect(iv).toBeLessThanOrEqual(9)
    // Defaults: min=0 max=100 when omitted.
    await player.runScene(['[random var="f.def"]', '[end]'].join(NL), 'rand_def.ks', { maxFrames: 200000, autoClick: true })
    const dv = await readF('def')
    expect(Number.isInteger(dv)).toBe(true)
    expect(dv).toBeGreaterThanOrEqual(0)
    expect(dv).toBeLessThanOrEqual(100)
    const errs = player.core.events.filter((e) => String(e.kind).includes('error'))
    expect(errs).toEqual([])
  }, 120000)

  it('[ending id=] records unlocked endings with dedup by id (round 82 parity)', async () => {
    // Isolate: reset the shared dedup registry so earlier scenes cannot leak.
    player.core.endings = []
    player.core._endingKeys = new Set()
    const NL = String.fromCharCode(10)
    // Two distinct ids + a repeat id. The engine keys seen_endings by id, so
    // a repeat OVERWRITES, not appends; recordEndings then dedups by id too.
    const out = await player.runScene(
      ['[ending id="good" name="Good End"]', '[ending id="bad"]', '[ending id="good"]', '[end]'].join(NL),
      'ending_multi.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    const ids = player.core.endings.map((e) => e.id)
    expect(ids).toContain('good')
    expect(ids).toContain('bad')
    // missing name falls back to "Ending <id>"
    expect(player.core.endings.find((e) => e.id === 'bad').name).toBe('Ending bad')
    // dedup: exactly two unique entries after the repeat [ending]
    expect(player.core.endings.length).toBe(2)

    // Across scenes: a fresh scene with the SAME id must not re-add it, and
    // ending.unlock fires only on a NEW id (not on the repeat).
    const before = player.core.endings.length
    await player.runScene(['[ending id="good"]', '[end]'].join(NL), 'ending_again.ks', { maxFrames: 200000, autoClick: true })
    expect(player.core.endings.length).toBe(before)
    const goodUnlocks = player.core.events.filter((e) => e.kind === 'ending.unlock' && e.detail.id === 'good').length
    expect(goodUnlocks).toBe(1)
  }, 120000)

  it('backlog preserves [p]-page order across a deep scrollback (round 82 parity)', async () => {
    player.core.backlog = []
    const NL = String.fromCharCode(10)
    const ks = []
    for (let i = 1; i <= 8; i++) ks.push('[ch name="N" text="LINE' + i + '"]', '[p]')
    ks.push('[end]')
    const out = await player.runScene(ks.join(NL), 'backlog_deep.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    // each [p] commits one page; arrival order is preserved (FIFO backlog)
    expect(player.core.backlog.length).toBe(8)
    expect(player.core.backlog.map((b) => b.text).join(' | ')).toBe(
      '[N]LINE1 | [N]LINE2 | [N]LINE3 | [N]LINE4 | [N]LINE5 | [N]LINE6 | [N]LINE7 | [N]LINE8')
    // pages carry the nameplate prefix [N] like the desktop history rows
    expect(player.core.backlog[0].text).toContain('[N]LINE1')
    expect(player.core.backlog[7].text).toContain('[N]LINE8')
  }, 120000)

  it('[rollback] before the first text point has no history and continues safely', async () => {
    const NL = String.fromCharCode(10)
    // The Web player uses the same runner and real undo stack as native.
    // Only the initial command below has no historical click point to restore.
    player.core.events.length = 0
    player.core.backlog = []
    const out = await player.runScene(
      ['[rollback]', '[ch name="N" text="A"]', '[p]', '[ch name="N" text="B"]', '[p]', '[end]'].join(NL),
      'rollback_deg.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    const errs = player.core.events.filter((e) => String(e.kind).includes('error'))
    expect(errs).toEqual([])
    // both lines still render; rollback did not abort or re-loop
    const texts = player.core.backlog.map((b) => b.text).join(' | ')
    expect(texts).toContain('A')
    expect(texts).toContain('B')
  }, 120000)

  it('[vibrate]/[flash] blocking VFX complete/degrade headless without crashing (round 82 parity)', async () => {
    const NL = String.fromCharCode(10)
    player.core.events.length = 0
    // [flash] (VFX.flash) and [vibrate] (KAG3 alias -> message-layer vib) are
    // BLOCKING: they yield frames until their duration elapses. Headless they
    // animate a pure-Lua flash layer / no-op message layer; the contract to
    // lock is that the scene completes with no error event.
    let out = await player.runScene(
      ['[flash r=255 g=0 b=0 time=100]', '[ch name="N" text="flash-done"]', '[p]', '[end]'].join(NL),
      'fx_flash.ks', { maxFrames: 200000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    expect(player.core.backlog.map((b) => b.text).join(' | ')).toContain('flash-done')

    player.core.events.length = 0
    player.core.backlog = []
    const out2 = await player.runScene(
      ['[vibrate time=100 intensity=3]', '[ch name="N" text="vib-done"]', '[p]', '[end]'].join(NL),
      'fx_vibrate.ks', { maxFrames: 200000, autoClick: true })
    expect(out2.startsWith('DONE:'), out2).toBe(true)
    expect(player.core.backlog.map((b) => b.text).join(' | ')).toContain('vib-done')

    const errs = player.core.events.filter((e) => String(e.kind).includes('error'))
    expect(errs).toEqual([])
  }, 120000)


  // ---- round 91: i18n web full-chain parity -------------------------------
  // The bridge now mounts the REAL assets/lang/{en,zh,ja}.lua dictionaries
  // into wasmoon's virtual FS, so i18n.load/set_language resolve genuine
  // files (plural items tables, per-lang fallback). These tests pin all
  // five parity axes from the round-91 spec: (1) real file loading reachable
  // by fetch path, (2) plural output matches desktop translate() per
  // language, (3) settings-set language actually switches the player and
  // redraws displayed text + persists across a settings "restart", (4)
  // tutorial_14's real {items} plural demo renders, (5) hot-switch re-localizes
  // backlog plural entries and governs new-page language after an advance,
  // (6) missing dictionary key -> fallback chain, plural value -> normal.

  // -- task 1 / 2: REAL lang files load; plural matches desktop per language
  it('round 91: real assets/lang dictionaries load (plural items table present)', async () => {
    // en is the dictionary the i18n.lua module booted from (mounted zh by
    // default; switch to en to inspect the genuine en table).
    await player.lua.doString('(require("i18n")).set_language("en")')
    const en = await player.lua.doString([
      "local I = require('i18n')",
      'return { current = I.current, settings = tostring(I.strings.settings or ""),',
      '         items = type(I.strings.items) ~= "table" and "notable" or',
      '         ("one=" .. tostring(I.strings.items.one) .. ";other=" .. tostring(I.strings.items.other)),',
      '         greeting = tostring(I.strings.greeting or "") }',
    ].join(String.fromCharCode(10)))
    expect(en.current).toBe('en')
    // genuine en dictionary string (not the built-in stub text)
    expect(en.settings).toBe('Settings')
    expect(en.greeting).toBe('Hello!')
    // the CLDR plural variant table shipped in assets/lang/en.lua is present
    expect(en.items).toContain('one={n} item')
    expect(en.items).toContain('other={n} items')
    // zh dictionary also resolves real values through the mounted file
    await player.lua.doString('(require("i18n")).set_language("zh")')
    const zh = await player.lua.doString("local I=require('i18n') return tostring(I.strings.settings or '')")
    expect(zh).toBe('设置')
  }, 120000)

  it('round 91: plural translate() output matches desktop for en (one/other) vs zh/ja (other)', async () => {
    const tNum = async (lang, key, n) => {
      await player.lua.doString('(require("i18n")).set_language(' + JSON.stringify(lang) + ')')
      await player.lua.doString('_G.__R = (require("i18n")).translate(' + JSON.stringify(key) + ', { n = ' + Number(n) + ' })')
      return player.lua.global.get('__R')
    }
    // en: n=1 -> one variant, n=3 -> other variant (real dict value)
    expect(await tNum('en', 'items', 1)).toBe('1 item')
    expect(await tNum('en', 'items', 3)).toBe('3 items')
    expect(await tNum('en', 'items', 0)).toBe('0 items')
    // zh/ja: always the single (other) form regardless of count
    expect(await tNum('zh', 'items', 1)).toBe('1 个条目')
    expect(await tNum('zh', 'items', 5)).toBe('5 个条目')
    expect(await tNum('ja', 'items', 1)).toBe('1 個')
    expect(await tNum('ja', 'items', 3)).toBe('3 個')
    // unknown language code also collapses to other (safe): current 'xx' has
    // no items key, so it falls back to the en fallback's OTHER form ({n} items)
    // with count 1 -> "1 items" (NOT the en one-form "1 item"). This pins the
    // zh/ja/unknown rule: everything except en uses the single "other" variant.
    expect(await tNum('xx', 'items', 1)).toBe('1 items')
  }, 120000)

  // -- task 1 / 6: missing lang file + missing key fallback chains
  it('round 91: a missing lang file degrades to built-in; missing key falls back en->raw', async () => {
    // 'zz' has no assets/lang/zz.lua on disk -> fileFetch 404s -> i18n uses
    // the built-in dictionary (zh), never throws.
    await player.lua.doString('(require("i18n")).set_language("zz")')
    const cur = await player.lua.doString("return (require('i18n')).current")
    expect(cur).toBe('zz')
    const builtinZh = await player.lua.doString("return tostring((require('i18n')).strings.title_screen or '')")
    expect(builtinZh).toBe('标题画面') // built-in zh table, not the file

    // Missing key: with en current, a key absent from both dict + fallback
    // returns the raw key unchanged.
    await player.lua.doString('(require("i18n")).set_language("en")')
    await player.lua.doString("_G.__R = (require('i18n')).t('totally_missing_key')")
    expect(player.lua.global.get('__R')).toBe('totally_missing_key')
    // A key present as a PLAIN string passes through normally (not a raw key).
    await player.lua.doString("_G.__R = (require('i18n')).t('greeting')")
    expect(player.lua.global.get('__R')).toBe('Hello!')
    // A key whose VALUE is a plural table resolves to the generic form via t()
    // (never leaks a raw table handle).
    await player.lua.doString("_G.__R = (require('i18n')).t('items')")
    expect(player.lua.global.get('__R')).toBe('{n} items')
  }, 120000)

  // -- task 3: settings.set('language') switches the player + redraws + persists
  it('round 91: player-settings language set switches i18n and re-localizes the displayed page', async () => {
    const { createPlayerSettings, makeMemoryStorage } = await import('./player-settings.js')
    const storage = makeMemoryStorage()
    const settings = createPlayerSettings({ storage })
    // wire the settings -> player language forwarder (mirrors main.mjs)
    settings.subscribe(({ field, settings: s }) => {
      if (field === 'language') void player.setLanguage(s.language)
    })

    // Render a page in zh, park at [p] so the ctx (and its page_src) stay live.
    const NL = String.fromCharCode(10)
    player.core.draws = []
    const zhKs = [
      '[i18n language="zh"]',
      '[ch name="N" text="t={settings}"]',
      '[p]',
      '[end]',
    ].join(NL)
    let out = await player.runScene(zhKs, 'rl_settings_zh.ks', { maxFrames: 200000, autoClick: false })
    expect(out.startsWith('WAIT:'), out).toBe(true)
    expect(player.core.draws.map((d) => d.t).join(' | ')).toContain('t=设置')

    // settings.set('language','en') -> applyLanguage -> player.setLanguage
    // must switch i18n.current AND relocalize the already-displayed page.
    settings.set('language', 'en')
    const cur = await player.lua.doString("return (require('i18n')).current")
    expect(cur).toBe('en')
    expect(player.core.draws.map((d) => d.t).join(' | ')).toContain('t=Settings')
    expect(player.core.draws.map((d) => d.t).join(' | ')).not.toContain('t=设置')

    // Persistence: a fresh settings controller from the SAME storage reloads ja.
    settings.set('language', 'ja')
    const settings2 = createPlayerSettings({ storage })
    expect(settings2.load().language).toBe('ja')
  }, 120000)

  // -- task 4: tutorial_14 real plural demo text content
  it('round 91: tutorial_14 renders the localized {items} plural demo text', async () => {
    const ks = readFileSync(join(here, '..', 'demo', 'tutorial', 'tutorial_14_flow_timing.ks'), 'utf8')
    player.core.events.length = 0
    player.core.backlog.length = 0
    const out = await player.runScene(ks, 'tutorial_14_flow_timing.ks', { maxFrames: 300000, autoClick: true })
    expect(out.startsWith('DONE:'), out).toBe(true)
    const errs = player.core.events.filter((e) => String(e.kind).includes('error'))
    expect(errs, 'tutorial_14 should have no error events').toEqual([])
    const texts = player.core.backlog
      .map((b) => b.text || '')
      .join(' | ')
      .concat(' | ' + player.core.events.filter((e) => e.kind === 'text.draws')
        .flatMap((e) => (Array.isArray(e.detail?.draws) ? e.detail.draws : []))
        .map((d) => d.t || '').join(' | '))
    // The [i18n language="en"] + [ch ... plural={items}] line renders the
    // genuine en plural "other" form (real assets/lang/en.lua value).
    expect(texts).toContain('plural={n} items')
    // The zh line renders the genuine zh other form.
    expect(texts).toContain('plural={n} 个条目')
    // The tutorial always completes (计时与流程教程完成. appears).
    expect(texts).toContain('计时与流程教程完成')
  }, 120000)

  // -- task 5: hot-switch re-localizes a backlog PLURAL entry; advance new page
  it('round 91: switching language re-localizes a backlog plural entry and steers the next page', async () => {
    const readBacklog = async () => {
      await player.lua.doString('_G.__R = _G.__LAST_CTX and _G.__LAST_CTX.backlog or nil')
      return player.lua.global.get('__R') || []
    }
    const NL = String.fromCharCode(10)
    const pageT = () => (player.core.draws || []).map((d) => d.t || '').join('')
    player.core.draws = []
    player.core.backlog.length = 0
    const ks = [
      '[i18n language="en"]',
      '[ch name="N" text="P1-{items}"]', '[p]',
      '[i18n language="zh"]',
      '[ch name="N" text="P2-{items}"]', '[p]',
      '[end]',
    ].join(NL)
    let out = await player.runScene(ks, 'i18n_plur_adv.ks', { maxFrames: 50000 })
    expect(out.startsWith('WAIT:'), out).toBe(true)
    expect(pageT()).toContain('P1-{n} items')

    out = await advanceTextPage(ks, 'i18n_plur_adv.ks')
    expect(out.startsWith('WAIT:'), out).toBe(true)
    expect(pageT()).toContain('P2-{n} 个条目')

    out = await advanceTextPage(ks, 'i18n_plur_adv.ks')
    expect(out.startsWith('DONE:'), out).toBe(true)
    const bl = await readBacklog()
    const blTexts = bl.map((b) => b.text || '')
    const blSrc = bl.map((b) => b.src || '')
    expect(bl.some((b) => b.text.includes('P1-{n} 个条目')), JSON.stringify(blTexts)).toBe(true)
    expect(bl.some((b) => b.text.includes('P1-{n} items')), JSON.stringify(blTexts)).toBe(false)
    expect(bl.some((b) => b.src === 'P1-{items}' && b.text.includes('P1-{n} 个条目')), JSON.stringify(blSrc)).toBe(true)
  }, 120000)

  // -- task 6 explicitly: missing key across per-language dicts
  it('round 91: a missing key in one language falls back to en, then raw; a plural VALUE stays normal', async () => {
    await player.lua.doString('(require("i18n")).set_language("ja")')
    await player.lua.doString("_G.__R = (require('i18n')).t('greeting')")
    expect(player.lua.global.get('__R')).toBe('こんにちは！')
    await player.lua.doString("_G.__R = (require('i18n')).t('items')")
    expect(player.lua.global.get('__R')).toBe('{n} 個')
    await player.lua.doString("_G.__R = (require('i18n')).t('no_such_key_anywhere')")
    expect(player.lua.global.get('__R')).toBe('no_such_key_anywhere')
  }, 120000)
})
